export const urbanDesignElements = [
  {
    id: "sunken-park",
    canonicalName: "Parque hundido",
    sourceNames: ["parque hundido", "espacio público vulnerable", "vacío urbano", "Parque Pedro Infante Hundido"],
    pages: [41, 45],
    function: "Lugar de intervención",
    environmentalIntentions: ["Cuenca urbana", "Susceptible a inundaciones", "Acumulación de calor"],
    socialIntentions: ["Espacio público en colonia popular"],
    structuralIntentions: [],
    relatedAssetIds: ["project-15-urban-opening-work", "project-15-urban-massing-model-work", "project-15-aerial-context-west-work"],
    relatedChapterIds: ["02", "04", "15"],
    distincitons: ["El parque comprende la totalidad del sitio, no solo los nodos"],
    warnings: ["aerial-images-comparison-undefined"],
    status: "confirmed"
  },
  {
    id: "urban-basin",
    canonicalName: "Cuenca urbana",
    sourceNames: ["cuenca urbana", "antigua sascabera"],
    pages: [41],
    function: "Lectura morfológica del sitio",
    environmentalIntentions: ["Continuidad hídrica del suelo", "Infiltración"],
    socialIntentions: [],
    structuralIntentions: [],
    relatedAssetIds: ["project-15-urban-massing-model-work"],
    relatedChapterIds: ["03", "07"],
    distincitons: ["Es un marco interpretativo de los autores, no una clasificación legal/técnica externa"],
    warnings: ["urban-basin-conceptual-status"],
    status: "confirmed"
  },
  {
    id: "elevated-spine",
    canonicalName: "Espina dorsal elevada",
    sourceNames: ["pasarela elevada", "espina dorsal elevada", "estructura ligera"],
    pages: [41, 43],
    function: "Circulación longitudinal y conexión",
    environmentalIntentions: ["Minimizar compactación del suelo", "Permitir permeabilidad transversal"],
    socialIntentions: ["Recorrido accesible"],
    structuralIntentions: ["Sistemas modulares", "Estructura ligera"],
    relatedAssetIds: ["project-15-site-master-plan-work", "project-15-elevated-spine-work"],
    relatedChapterIds: ["09"],
    distincitons: ["Cruza transversalmente el parque, uniendo el tejido urbano fragmentado"],
    warnings: ["elevated-spine-terminology"],
    status: "confirmed"
  },
  {
    id: "central-ring",
    canonicalName: "Anillo central",
    sourceNames: ["anillo central", "nodo central circular", "sistema anular", "espacio circular", "foro central"],
    pages: [41, 43, 44],
    function: "Nodo principal de permanencia y sombra",
    environmentalIntentions: ["Sombra densa", "Ventilación", "Respuesta a clima tropical"],
    socialIntentions: ["Convergencia comunitaria", "Asamblea"],
    structuralIntentions: ["Cubierta ligera", "Gradas circulares"],
    relatedAssetIds: ["project-15-site-master-plan-work", "project-15-central-ring-axonometric-work"],
    relatedChapterIds: ["10", "13"],
    distincitons: ["No confundir con el anillo de juego de la página 45"],
    warnings: ["circular-nodes-distinction", "community-participation-not-documented"],
    status: "confirmed"
  },
  {
    id: "sunken-amphitheater",
    canonicalName: "Anfiteatro hundido",
    sourceNames: ["anfiteatro hundido", "anfiteatro"],
    pages: [41, 42, 43],
    function: "Retención hídrica y uso público flexible",
    environmentalIntentions: ["Captación hídrica temporal", "Infiltración"],
    socialIntentions: ["Espacio de reunión cuando no está inundado"],
    structuralIntentions: ["Diseño topográfico hundido"],
    relatedAssetIds: ["project-15-amphitheater-plan-work", "project-15-site-master-plan-work"],
    relatedChapterIds: ["11"],
    distincitons: ["Es distinto al anillo central techado"],
    warnings: ["environmental-performance-not-quantified"],
    status: "confirmed"
  },
  {
    id: "radial-path-system",
    canonicalName: "Sistema radial",
    sourceNames: ["sistema radial", "recorridos radiales", "senderos"],
    pages: [42, 43],
    function: "Distribución de flujos peatonales",
    environmentalIntentions: ["Adaptación a topografía existente"],
    socialIntentions: ["Accesibilidad perimetral"],
    structuralIntentions: [],
    relatedAssetIds: ["project-15-radial-plan-work", "project-15-site-master-plan-work"],
    relatedChapterIds: ["08"],
    distincitons: [],
    warnings: [],
    status: "confirmed"
  },
  {
    id: "strategic-vegetation",
    canonicalName: "Vegetación estratégica",
    sourceNames: ["infraestructura verde", "masas arbóreas", "vegetación", "sombra"],
    pages: [41, 42, 43, 44, 45],
    function: "Confort térmico y control hídrico",
    environmentalIntentions: ["Reducir calor", "Filtrar radiación solar", "Sombra estacional", "Favorecer infiltración"],
    socialIntentions: ["Confort en áreas de estancia"],
    structuralIntentions: [],
    relatedAssetIds: ["project-15-site-master-plan-work", "project-15-preliminary-plan-work"],
    relatedChapterIds: ["12"],
    distincitons: ["Diseñada en clústeres, no de forma uniforme"],
    warnings: ["environmental-performance-not-quantified"],
    status: "confirmed"
  },
  {
    id: "play-ring",
    canonicalName: "Anillo de juego",
    sourceNames: ["espacio de juego", "anillo de juego", "estructura de juego", "plataformas circulares"],
    pages: [45],
    function: "Equipamiento lúdico",
    environmentalIntentions: ["Integración topográfica"],
    socialIntentions: ["Juego", "Movimiento corporal libre"],
    structuralIntentions: ["Plataformas circulares interconectadas", "Arco central"],
    relatedAssetIds: ["project-15-play-ring-render-work"],
    relatedChapterIds: ["14"],
    distincitons: ["Secundario respecto al anillo central. Enfocado a población infantil"],
    warnings: [],
    status: "confirmed"
  }
];
