export const urbanAssets = [
  // DIAGNÓSTICO Y CONTEXTO
  {
    id: "project-15-urban-opening-work",
    sourcePage: 41,
    sourceBounds: "full-width-image",
    type: "editorial-opening",
    subtype: "image",
    designPhase: "diagnostic",
    chapterIds: ["00", "01"],
    roleCandidates: ["hero-candidate", "editorial-opening"],
    previewPath: "/portfolio-media/curated/project-15/work/opening/project-15-urban-opening-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/opening/project-15-urban-opening-work.webp",
    expectedFinalVariants: ["desktop", "mobile"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "medium",
    semanticConfidence: "low",
    credit: "restricted-until-reviewed",
    source: "Portfolio p. 41",
    licenseStatus: "pending",
    warnings: ["verify-cultural-origin"],
    status: "restricted"
  },
  {
    id: "project-15-urban-massing-model-work",
    sourcePage: 42,
    sourceBounds: "top-left",
    type: "urban-context-model",
    subtype: "massing-model",
    designPhase: "diagnostic",
    chapterIds: ["04", "05"],
    roleCandidates: ["context"],
    previewPath: "/portfolio-media/curated/project-15/work/site/project-15-urban-massing-model-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/site/project-15-urban-massing-model-work.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  {
    id: "project-15-aerial-context-west-work",
    sourcePage: 45,
    sourceBounds: "bottom-left",
    type: "site-aerial",
    subtype: "capture",
    designPhase: "diagnostic",
    chapterIds: ["15"],
    roleCandidates: ["context"],
    previewPath: "/portfolio-media/curated/project-15/work/aerial-context/project-15-aerial-context-west-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/aerial-context/project-15-aerial-context-west-work.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "pending-verification",
    source: "Portfolio p. 45",
    licenseStatus: "pending",
    warnings: ["aerial-images-comparison-undefined"],
    status: "unverified"
  },
  {
    id: "project-15-aerial-context-east-work",
    sourcePage: 45,
    sourceBounds: "bottom-right",
    type: "site-aerial",
    subtype: "capture",
    designPhase: "diagnostic",
    chapterIds: ["15"],
    roleCandidates: ["context"],
    previewPath: "/portfolio-media/curated/project-15/work/aerial-context/project-15-aerial-context-east-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/aerial-context/project-15-aerial-context-east-work.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "pending-verification",
    source: "Portfolio p. 45",
    licenseStatus: "pending",
    warnings: ["aerial-images-comparison-undefined"],
    status: "unverified"
  },

  // ESQUEMA
  {
    id: "project-15-preliminary-plan-work",
    sourcePage: 42,
    sourceBounds: "center-left",
    type: "preliminary-plan",
    subtype: "diagram",
    designPhase: "schema",
    chapterIds: ["05", "06"],
    roleCandidates: ["schema"],
    previewPath: "/portfolio-media/curated/project-15/work/site/project-15-preliminary-plan-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/site/project-15-preliminary-plan-work.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  {
    id: "project-15-radial-plan-work",
    sourcePage: 42,
    sourceBounds: "bottom-left",
    type: "radial-plan",
    subtype: "diagram",
    designPhase: "schema",
    chapterIds: ["08"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/work/master-plan/project-15-radial-plan-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/master-plan/project-15-radial-plan-work.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },

  // DESARROLLO (MASTER PLAN Y SISTEMAS)
  {
    id: "project-15-site-master-plan-work",
    sourcePage: 43,
    sourceBounds: "full-width",
    type: "master-plan",
    subtype: "detailed-plan",
    designPhase: "development",
    chapterIds: ["08", "09", "10", "11", "12"],
    roleCandidates: ["hero-candidate", "primary-map"],
    previewPath: "/portfolio-media/curated/project-15/work/master-plan/project-15-site-master-plan-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/master-plan/project-15-site-master-plan-work.webp",
    expectedFinalVariants: ["desktop", "mobile"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  {
    id: "project-15-elevated-spine-work",
    sourcePage: 43,
    sourceBounds: "bottom-left",
    type: "axonometric",
    subtype: "diagram",
    designPhase: "development",
    chapterIds: ["09"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/work/elevated-spine/project-15-elevated-spine-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/elevated-spine/project-15-elevated-spine-work.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: ["elevated-spine-terminology"],
    status: "confirmed"
  },

  // DETALLE
  {
    id: "project-15-central-ring-axonometric-work",
    sourcePage: 44,
    sourceBounds: "top",
    type: "axonometric",
    subtype: "detailed-render",
    designPhase: "detail",
    chapterIds: ["10", "13"],
    roleCandidates: ["hero-candidate", "primary-view"],
    previewPath: "/portfolio-media/curated/project-15/work/central-ring/project-15-central-ring-axonometric-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/central-ring/project-15-central-ring-axonometric-work.webp",
    expectedFinalVariants: ["desktop", "mobile"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 44",
    licenseStatus: "cleared",
    warnings: ["circular-nodes-distinction"],
    status: "confirmed"
  },
  {
    id: "project-15-play-ring-render-work",
    sourcePage: 45,
    sourceBounds: "top",
    type: "play-render",
    subtype: "perspective",
    designPhase: "detail",
    chapterIds: ["14"],
    roleCandidates: ["hero-candidate", "primary-view"],
    previewPath: "/portfolio-media/curated/project-15/work/play/project-15-play-ring-render-work.webp",
    workPath: "/portfolio-media/curated/project-15/work/play/project-15-play-ring-render-work.webp",
    expectedFinalVariants: ["desktop", "mobile"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 45",
    licenseStatus: "cleared",
    warnings: ["community-participation-not-documented"],
    status: "confirmed"
  },
  
  // ==========================================
  // BLOQUE 25: LECTURA DEL SITIO (PÁGINA 42)
  // ==========================================

  // AUDITORÍAS PÁGINA 42
  {
    id: "page-42-complete-audit",
    sourcePage: 42,
    sourceBounds: "full-width",
    type: "audit",
    subtype: "document-analysis",
    designPhase: "diagnostic",
    chapterIds: ["04", "05", "06", "07"],
    roleCandidates: ["audit"],
    previewPath: "/portfolio-media/audit/block-25/page-42-complete-audit.png",
    workPath: "/portfolio-media/audit/block-25/page-42-complete-audit.png",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  {
    id: "page-42-text-resource-association",
    sourcePage: 42,
    sourceBounds: "full-width",
    type: "audit",
    subtype: "document-analysis",
    designPhase: "diagnostic",
    chapterIds: ["04", "05", "06", "07"],
    roleCandidates: ["audit"],
    previewPath: "/portfolio-media/audit/block-25/page-42-text-resource-association.png",
    workPath: "/portfolio-media/audit/block-25/page-42-text-resource-association.png",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  {
    id: "page-42-diagnostic-proposal-split",
    sourcePage: 42,
    sourceBounds: "full-width",
    type: "audit",
    subtype: "document-analysis",
    designPhase: "diagnostic",
    chapterIds: ["04", "05", "06", "07"],
    roleCandidates: ["audit"],
    previewPath: "/portfolio-media/audit/block-25/page-42-diagnostic-proposal-split.png",
    workPath: "/portfolio-media/audit/block-25/page-42-diagnostic-proposal-split.png",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },

  // TEJIDO URBANO (URBAN FABRIC)
  {
    id: "project-15-urban-fabric-model-a-full",
    sourcePage: 42,
    sourceBounds: "top-left",
    type: "urban-context-model",
    subtype: "massing-model",
    designPhase: "diagnostic",
    chapterIds: ["04", "05"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/urban-fabric/project-15-urban-fabric-model-a-full.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/urban-fabric/project-15-urban-fabric-model-a-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: ["urban-fabric-homogeneity-not-quantified"],
    status: "confirmed"
  },
  {
    id: "project-15-urban-fabric-model-b-full",
    sourcePage: 42,
    sourceBounds: "top-right",
    type: "urban-context-model",
    subtype: "massing-model",
    designPhase: "diagnostic",
    chapterIds: ["04", "06"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/urban-fabric/project-15-urban-fabric-model-b-full.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/urban-fabric/project-15-urban-fabric-model-b-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: ["wind-overlay-association-partial"],
    status: "confirmed"
  },
  {
    id: "project-15-urban-fabric-comparison",
    sourcePage: 42,
    sourceBounds: "top",
    type: "urban-context-model",
    subtype: "comparison",
    designPhase: "diagnostic",
    chapterIds: ["04"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/urban-fabric/project-15-urban-fabric-comparison.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/urban-fabric/project-15-urban-fabric-comparison.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: ["page-42-analysis-methods-not-documented"],
    status: "confirmed"
  },

  // BORDES Y ACCESOS (EDGES ACCESS)
  {
    id: "project-15-edges-access-context-preview",
    sourcePage: 42,
    sourceBounds: "top-left",
    type: "urban-context-model",
    subtype: "massing-model",
    designPhase: "diagnostic",
    chapterIds: ["05"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/edges-access/project-15-edges-access-context-preview.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/edges-access/project-15-edges-access-context-preview.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: ["potential-accesses-not-spatially-documented"],
    status: "confirmed"
  },

  // CLIMA (CLIMATE)
  {
    id: "project-15-climate-reading-full",
    sourcePage: 42,
    sourceBounds: "top-right",
    type: "conceptual-climate-overlay",
    subtype: "diagram",
    designPhase: "diagnostic",
    chapterIds: ["06"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/climate/project-15-climate-reading-full.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/climate/project-15-climate-reading-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: ["wind-overlay-association-partial", "thermal-zones-not-visually-mapped"],
    status: "confirmed"
  },
  {
    id: "project-15-possible-wind-overlay",
    sourcePage: 42,
    sourceBounds: "top-right",
    type: "conceptual-climate-overlay",
    subtype: "diagram",
    designPhase: "diagnostic",
    chapterIds: ["06"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/climate/project-15-possible-wind-overlay.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/climate/project-15-possible-wind-overlay.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: ["wind-overlay-association-partial"],
    status: "confirmed"
  },

  // TOPOGRAFÍA Y AGUA
  {
    id: "project-15-topography-water-context-full",
    sourcePage: 42,
    sourceBounds: "center",
    type: "site-plan-fragment",
    subtype: "diagram",
    designPhase: "schema",
    chapterIds: ["07"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/topography-water/project-15-topography-water-context-full.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/topography-water/project-15-topography-water-context-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: ["topography-not-quantified", "hydrological-behavior-not-modeled"],
    status: "confirmed"
  },

  // ANTICIPACIÓN PROPUESTA
  {
    id: "project-15-site-response-preview",
    sourcePage: 42,
    sourceBounds: "bottom-left",
    type: "site-plan-fragment",
    subtype: "diagram",
    designPhase: "schema",
    chapterIds: ["04", "05", "06", "07"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/site-reading/proposal-preview/project-15-site-response-preview.webp",
    workPath: "/portfolio-media/curated/project-15/site-reading/proposal-preview/project-15-site-response-preview.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 42",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  
  // ==========================================
  // BLOQUE 26: SISTEMA DE INTERVENCIÓN (PÁGINA 43)
  // ==========================================

  // AUDITORÍAS PÁGINA 43
  {
    id: "page-43-complete-audit",
    sourcePage: 43,
    sourceBounds: "full-width",
    type: "audit",
    subtype: "document-analysis",
    designPhase: "development",
    chapterIds: ["08", "09", "11", "12"],
    roleCandidates: ["audit"],
    previewPath: "/portfolio-media/audit/block-26/page-43-complete-audit.png",
    workPath: "/portfolio-media/audit/block-26/page-43-complete-audit.png",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  {
    id: "page-43-master-plan-candidates",
    sourcePage: 43,
    sourceBounds: "full-width",
    type: "audit",
    subtype: "document-analysis",
    designPhase: "development",
    chapterIds: ["08"],
    roleCandidates: ["audit"],
    previewPath: "/portfolio-media/audit/block-26/page-43-master-plan-candidates.png",
    workPath: "/portfolio-media/audit/block-26/page-43-master-plan-candidates.png",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },

  // PLAN MAESTRO
  {
    id: "project-15-master-plan-full",
    sourcePage: 43,
    sourceBounds: "right",
    type: "master-plan",
    subtype: "detailed-plan",
    designPhase: "development",
    chapterIds: ["08"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/intervention-system/master-plan/project-15-master-plan-full.webp",
    workPath: "/portfolio-media/curated/project-15/intervention-system/master-plan/project-15-master-plan-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: ["master-plan-editorial-label", "page-43-scale-dimensions-not-documented"],
    status: "confirmed"
  },
  {
    id: "project-15-master-plan-system-detail",
    sourcePage: 43,
    sourceBounds: "right",
    type: "master-plan",
    subtype: "detailed-plan",
    designPhase: "development",
    chapterIds: ["08"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/intervention-system/master-plan/project-15-master-plan-system-detail.webp",
    workPath: "/portfolio-media/curated/project-15/intervention-system/master-plan/project-15-master-plan-system-detail.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },

  // ESPINA DORSAL
  {
    id: "project-15-elevated-spine-full",
    sourcePage: 43,
    sourceBounds: "bottom-left",
    type: "elevated-circulation",
    subtype: "architectural-perspective",
    designPhase: "development",
    chapterIds: ["09"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/intervention-system/elevated-spine/project-15-elevated-spine-full.webp",
    workPath: "/portfolio-media/curated/project-15/intervention-system/elevated-spine/project-15-elevated-spine-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: ["continuous-shade-not-measured", "page-43-environmental-performance-not-verified"],
    status: "confirmed"
  },

  // ANFITEATRO
  {
    id: "project-15-amphitheater-full",
    sourcePage: 43,
    sourceBounds: "right",
    type: "amphitheater-plan",
    subtype: "site-system-detail",
    designPhase: "development",
    chapterIds: ["11"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/intervention-system/amphitheater/project-15-amphitheater-full.webp",
    workPath: "/portfolio-media/curated/project-15/intervention-system/amphitheater/project-15-amphitheater-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: ["amphitheater-figure-identification", "page-43-scale-dimensions-not-documented"],
    status: "confirmed"
  },

  // VEGETACIÓN E INFILTRACIÓN
  {
    id: "project-15-vegetation-infiltration-full",
    sourcePage: 43,
    sourceBounds: "right",
    type: "vegetation-plan",
    subtype: "integrated-site-plan",
    designPhase: "development",
    chapterIds: ["12"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/intervention-system/vegetation-infiltration/project-15-vegetation-infiltration-full.webp",
    workPath: "/portfolio-media/curated/project-15/intervention-system/vegetation-infiltration/project-15-vegetation-infiltration-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    warnings: ["existing-proposed-vegetation-not-separated", "hydrological-behavior-not-modeled"],
    status: "confirmed"
  },

  // TRANSICIÓN FINAL AL ANILLO (PREVIEW)
  {
    id: "project-15-system-to-central-ring-preview",
    sourcePage: 43,
    sourceBounds: "top",
    type: "circular-node",
    subtype: "site-system-detail",
    designPhase: "development",
    chapterIds: ["10"],
    roleCandidates: ["detail"],
    previewPath: "/portfolio-media/curated/project-15/intervention-system/central-ring-preview/project-15-system-to-central-ring-preview.webp",
    workPath: "/portfolio-media/curated/project-15/intervention-system/central-ring-preview/project-15-system-to-central-ring-preview.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 43",
    licenseStatus: "cleared",
    status: "confirmed"
  },
  
  // ==========================================
  // BLOQUE 27: CIERRE (PÁGINAS 44-45)
  // ==========================================

  // AUDITORÍAS
  {
    id: "page-44-complete-audit",
    sourcePage: 44,
    sourceBounds: "full-width",
    type: "audit",
    subtype: "document-analysis",
    designPhase: "development",
    chapterIds: ["10", "13"],
    roleCandidates: ["audit"],
    previewPath: "/portfolio-media/audit/block-27/page-44-complete-audit.png",
    workPath: "/portfolio-media/audit/block-27/page-44-complete-audit.png",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 44",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },
  {
    id: "page-45-complete-audit",
    sourcePage: 45,
    sourceBounds: "full-width",
    type: "audit",
    subtype: "document-analysis",
    designPhase: "development",
    chapterIds: ["14", "15"],
    roleCandidates: ["audit"],
    previewPath: "/portfolio-media/audit/block-27/page-45-complete-audit.png",
    workPath: "/portfolio-media/audit/block-27/page-45-complete-audit.png",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 45",
    licenseStatus: "cleared",
    warnings: [],
    status: "confirmed"
  },

  // ANILLO CENTRAL (CAPÍTULO 10)
  {
    id: "project-15-central-ring-axonometric-full",
    sourcePage: 44,
    sourceBounds: "top-right",
    type: "central-ring-axonometric",
    subtype: "detailed-plan",
    designPhase: "development",
    chapterIds: ["10"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/final-system/central-ring/project-15-central-ring-axonometric-full.webp",
    workPath: "/portfolio-media/curated/project-15/final-system/central-ring/project-15-central-ring-axonometric-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: false,
    preserveCaption: false,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 44",
    licenseStatus: "cleared",
    warnings: ["central-ring-climate-performance-not-measured", "central-ring-permeable-surface-not-quantified"],
    status: "confirmed"
  },
  {
    id: "project-15-central-ring-left-perspective-full",
    sourcePage: 44,
    sourceBounds: "bottom-left",
    type: "central-ring-perspective",
    subtype: "architectural-perspective",
    designPhase: "development",
    chapterIds: ["10", "13"],
    roleCandidates: ["detail", "hero"],
    previewPath: "/portfolio-media/curated/project-15/final-system/central-ring/project-15-central-ring-left-perspective-full.webp",
    workPath: "/portfolio-media/curated/project-15/final-system/central-ring/project-15-central-ring-left-perspective-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: false,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "medium",
    credit: "original",
    source: "Portfolio p. 44",
    licenseStatus: "cleared",
    warnings: ["community-participation-not-documented"],
    status: "confirmed"
  },

  // NODO COMUNITARIO (CAPÍTULO 13)
  {
    id: "project-15-community-node-full",
    sourcePage: 44,
    sourceBounds: "bottom-left",
    type: "community-space-render",
    subtype: "architectural-perspective",
    designPhase: "development",
    chapterIds: ["13"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/final-system/community-node/project-15-community-node-full.webp",
    workPath: "/portfolio-media/curated/project-15/final-system/community-node/project-15-community-node-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "container",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 44",
    licenseStatus: "cleared",
    warnings: ["community-participation-not-documented"],
    status: "confirmed"
  },

  // ANILLO DE JUEGO (CAPÍTULO 14)
  {
    id: "project-15-play-ring-full",
    sourcePage: 45,
    sourceBounds: "top",
    type: "play-ring-render",
    subtype: "architectural-perspective",
    designPhase: "development",
    chapterIds: ["14"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/final-system/play-ring/project-15-play-ring-full.webp",
    workPath: "/portfolio-media/curated/project-15/final-system/play-ring/project-15-play-ring-full.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 45",
    licenseStatus: "cleared",
    warnings: ["central-ring-play-ring-distinction"],
    status: "confirmed"
  },
  
  // CONTEXTO AÉREO / CIERRE (CAPÍTULO 15)
  {
    id: "project-15-aerial-context-pair-preview",
    sourcePage: 45,
    sourceBounds: "bottom",
    type: "aerial-context",
    subtype: "map-screenshot",
    designPhase: "context",
    chapterIds: ["15"],
    roleCandidates: ["primary-view"],
    previewPath: "/portfolio-media/curated/project-15/final-system/aerial-context/project-15-aerial-context-pair-preview.webp",
    workPath: "/portfolio-media/curated/project-15/final-system/aerial-context/project-15-aerial-context-pair-preview.webp",
    expectedFinalVariants: ["default"],
    preserveContext: true,
    preserveCaption: true,
    preserveMapCredits: true,
    readableAt: "fullscreen",
    cropConfidence: "high",
    semanticConfidence: "high",
    credit: "original",
    source: "Portfolio p. 45",
    licenseStatus: "usable-with-visible-attribution",
    warnings: ["urban-challenge-built-status"],
    status: "confirmed"
  }
];
