export const urbanClaims = [
  {
    id: "claim-urban-competition",
    exactSourceText: "Proyecto correspondiente a un concurso universitario",
    normalizedText: "Concurso Universitario",
    page: 41,
    chapterId: "01",
    elementId: "context",
    type: "direct-text",
    sourceStatus: "verified",
    associationConfidence: "high",
    publicUseRecommendation: "Utilizar como estado oficial del proyecto.",
    requiresVerification: false,
    warnings: ["urban-challenge-built-status"]
  },
  {
    id: "claim-urban-basin",
    exactSourceText: "cuenca urbana",
    normalizedText: "Cuenca urbana",
    page: 41,
    chapterId: "03",
    elementId: "urban-basin",
    type: "source-interpretation",
    sourceStatus: "verified",
    associationConfidence: "high",
    publicUseRecommendation: "Utilizar con prudencia como lectura conceptual (no delimitación hidrológica formal).",
    requiresVerification: true,
    warnings: ["urban-basin-conceptual-status"]
  },
  {
    id: "claim-urban-climate-risks",
    exactSourceText: "riesgos climáticos, hídricos y térmicos",
    normalizedText: "Riesgos climáticos, hídricos y térmicos",
    page: 41,
    chapterId: "03",
    elementId: "site",
    type: "direct-text",
    sourceStatus: "verified",
    associationConfidence: "high",
    publicUseRecommendation: "Acompañar con aclaración de que el proyecto no presenta métricas.",
    requiresVerification: false,
    warnings: []
  },
  {
    id: "claim-urban-floods",
    exactSourceText: "inundaciones y acumulación de calor",
    normalizedText: "Susceptibilidad a inundaciones y acumulación de calor",
    page: 41,
    chapterId: "03",
    elementId: "site",
    type: "direct-text",
    sourceStatus: "verified",
    associationConfidence: "high",
    publicUseRecommendation: "Redactar como 'espacio susceptible a', no como hecho documentado con métricas.",
    requiresVerification: false,
    warnings: []
  },
  {
    id: "claim-urban-thermal-behavior",
    exactSourceText: "comportamiento térmico",
    normalizedText: "Comportamiento térmico y ventilación cruzada",
    page: 42,
    chapterId: "06",
    elementId: "site",
    type: "design-intention",
    sourceStatus: "verified",
    associationConfidence: "medium",
    publicUseRecommendation: "Mantener como intención del diseño. No construir mapas de simulación térmica interactiva.",
    requiresVerification: true,
    warnings: ["wind-thermal-simulation-undocumented"]
  },
  {
    id: "claim-urban-infiltration",
    exactSourceText: "favorecer infiltración",
    normalizedText: "Favorecer infiltración",
    page: 43,
    chapterId: "12",
    elementId: "strategic-vegetation",
    type: "performance-not-verified",
    sourceStatus: "verified",
    associationConfidence: "high",
    publicUseRecommendation: "Mantener como intención de diseño. No cuantificar m³ infiltrados.",
    requiresVerification: false,
    warnings: ["environmental-performance-not-quantified"]
  },
  {
    id: "claim-urban-pedro-infante",
    exactSourceText: "Parque Pedro Infante Hundido",
    normalizedText: "Parque Pedro Infante Hundido",
    page: 45,
    chapterId: "02",
    elementId: "sunken-park",
    type: "direct-figure",
    sourceStatus: "verified",
    associationConfidence: "high",
    publicUseRecommendation: "Se puede usar como etiqueta, pero el título del caso debe priorizar 'Parque Hundido' genérico.",
    requiresVerification: false,
    warnings: []
  },
  {
    id: "claim-urban-community",
    exactSourceText: "convergencia comunitaria, asamblea, juego",
    normalizedText: "Convergencia comunitaria y juego",
    page: 44,
    chapterId: "13",
    elementId: "central-ring",
    type: "design-intention",
    sourceStatus: "verified",
    associationConfidence: "high",
    publicUseRecommendation: "Redactar como vocación del espacio, no como participación o codiseño vecinal comprobado.",
    requiresVerification: false,
    warnings: ["community-participation-not-documented"]
  }
];
