/**
 * Pruebas de regresión de la entrega.
 *
 * Cada una corresponde a un defecto que llegó a estar en el sitio o en el PDF y
 * que no se ve en una revisión rápida: una grafía del nombre, un archivo de
 * impresión servido por debajo de su caja, un dato duplicado a mano que dejó de
 * coincidir con su gráfica. Son comprobaciones de archivo, no de navegador: el
 * recorrido visual lo cubren `qa:rutas`, `qa:navegacion` y `qa:visual`.
 */
import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';

const PDF = 'public/downloads/Nestor-Arriaga-Gallegos-Portafolio-2026.pdf';

/** Todos los archivos de código y contenido publicados. */
function fuentes(dir = 'src', acc = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const f = join(dir, e.name);
    if (e.isDirectory()) fuentes(f, acc);
    else if (/\.(tsx?|css)$/.test(e.name)) acc.push(f);
  }
  return acc;
}

const archivos = fuentes();
const todo = archivos.map((f) => [f, readFileSync(f, 'utf8')]);

/* --- Autoría ---------------------------------------------------------------- */

test('el nombre del autor va sin acento en todo el proyecto', () => {
  const conAcento = todo.filter(([, s]) => s.includes('Néstor')).map(([f]) => f);
  assert.deepEqual(conAcento, [], `«Néstor» aparece en: ${conAcento.join(', ')}`);
});

test('la identidad publica el nombre completo', () => {
  const id = readFileSync('src/content/identity.ts', 'utf8');
  assert.match(id, /Nestor Elihu Arriaga Gallegos/);
});

/* --- Rastros del proceso ----------------------------------------------------- */

test('no quedan rastros del proceso asistido en el código publicado', () => {
  const rastro = /\b(Gemini|ChatGPT|OpenAI|Copilot|generated by AI)\b|the prompt|requested it/i;
  const sucios = todo.filter(([, s]) => rastro.test(s)).map(([f]) => f);
  assert.deepEqual(sucios, [], `rastros en: ${sucios.join(', ')}`);
});

test('no quedan marcas temporales de desarrollo', () => {
  // Sin `i`: las marcas van en mayúsculas por convención y en español «todo:»
  // es una palabra corriente que aparece en los comentarios.
  const marca = /\bTODO:|\bFIXME\b|\bXXX\b|\bHACK:/;
  const sucios = todo
    .filter(([, s]) => marca.test(s) || /lorem ipsum/i.test(s))
    .map(([f]) => f);
  assert.deepEqual(sucios, [], `marcas en: ${sucios.join(', ')}`);
});

/* --- Coherencia de los datos de clustering ----------------------------------- */

test('los porcentajes de clustering se calculan, no se escriben', async () => {
  const { clusteringGrupos, clusteringClasificados, clusteringPorcentaje, comarcaMunicipios } =
    await modulo('src/content/granularClustering.ts');

  assert.equal(clusteringGrupos.length, 3);
  assert.deepEqual(clusteringGrupos.map((g) => g.municipios), [7, 4, 3]);
  assert.equal(clusteringClasificados, 14);
  assert.equal(comarcaMunicipios, 15);

  const pct = clusteringGrupos.map((g) => +clusteringPorcentaje(g).toFixed(1));
  assert.deepEqual(pct, [50, 28.6, 21.4]);
  // La suma de los grupos es el total clasificado: si alguien cambia un conteo
  // sin tocar el resto, esta igualdad deja de cumplirse.
  assert.equal(clusteringGrupos.reduce((a, g) => a + g.municipios, 0), clusteringClasificados);
});

test('el color de cada grupo es el de la leyenda del mapa', async () => {
  const { clusteringGrupos } = await modulo('src/content/granularClustering.ts');
  // Cian, magenta y ámbar, muestreados de la leyenda de «Tipología funcional».
  assert.deepEqual(clusteringGrupos.map((g) => g.color), ['#00c5e0', '#e51c69', '#efc518']);
});

/* --- Impresión ---------------------------------------------------------------- */

test('ninguna figura declara un derivado de impresión de 960 px', () => {
  const vis = readFileSync('src/content/granularVisuals.ts', 'utf8');
  assert.doesNotMatch(vis, /printSrc: '[^']*-960\./,
    'un derivado de 960 px no sostiene una lámina impresa dominante');
});

test('cada figura de GRANULAR publica su escalera de impresión', () => {
  const vis = readFileSync('src/content/granularVisuals.ts', 'utf8');
  const conPrint = vis.match(/printSrc:/g)?.length ?? 0;
  const conEscalera = vis.match(/printSrcSet:/g)?.length ?? 0;
  assert.ok(conPrint > 0, 'no hay fuentes de impresión declaradas');
  assert.equal(conEscalera, conPrint, 'hay fuentes de impresión sin escalera');
});

test('el derivado de impresión elegido cubre su caja', async () => {
  const { pixelesPara, anchoImpreso } = await modulo('src/components/impreso/densidadImpresa.ts');
  const img = {
    src: '/a-2480.webp',
    srcSet: '/a-960.webp 960w, /a-1440.webp 1440w, /a-2480.webp 2480w',
    width: 2480,
  };
  // Una caja de 186 mm a 200 ppp pide 1465 px: el derivado de 1440 no llega y
  // se sube al siguiente. Una de 92 mm pide 725 y le basta el de 960.
  assert.equal(pixelesPara(186), 1465);
  assert.equal(anchoImpreso(img, 186), 2480);
  assert.equal(pixelesPara(92), 725);
  assert.equal(anchoImpreso(img, 92), 960);
  assert.equal(anchoImpreso(img, 130), 1440);
});

/* --- El archivo entregado ------------------------------------------------------ */

test('el PDF existe, pesa lo declarado y está por debajo del límite', () => {
  assert.ok(existsSync(PDF), 'no hay PDF generado');
  const mb = statSync(PDF).size / 1024 / 1024;
  assert.ok(mb < 40, `el PDF pesa ${mb.toFixed(1)} MB y el límite es 40`);
  assert.ok(mb > 8, `el PDF pesa ${mb.toFixed(1)} MB: demasiado poco para su resolución`);
});

test('el contador de descarga se mide sobre el archivo real', () => {
  const reg = readFileSync('src/components/experience-v5/registry.ts', 'utf8');
  // Ni el peso ni el número de páginas pueden estar escritos a mano.
  assert.match(reg, /buf\.length \/ 1024 \/ 1024/);
  assert.match(reg, /\/Type\\s\*\\\/Page/);
});

test('el PDF declara autoría, título y estructura etiquetada', async () => {
  const zlib = await import('node:zlib');
  const buf = readFileSync(PDF);

  // Tras linearizar, los diccionarios viajan dentro de flujos de objetos, así
  // que buscar en el archivo en crudo no basta: hay que descomprimirlos.
  const partes = [buf.toString('latin1')];
  for (const m of buf.toString('latin1').matchAll(/stream\r?\n/g)) {
    const ini = m.index + m[0].length;
    const fin = buf.indexOf('endstream', ini, 'latin1');
    if (fin < 0) continue;
    try { partes.push(zlib.inflateSync(buf.subarray(ini, fin)).toString('latin1')); } catch { /* no comprimido */ }
  }
  // qpdf reescribe las cadenas hexadecimales en minúsculas al reordenar, así
  // que la comparación no puede depender de la caja.
  const texto = partes.join('\n').toLowerCase();
  const hex = Buffer.from('\ufeffNestor Elihu Arriaga Gallegos', 'utf16le')
    .swap16().toString('hex').toLowerCase();

  assert.ok(texto.includes(hex), 'sin autoría en los metadatos');
  assert.ok(texto.includes('/markinfo') || texto.includes('/structtreeroot'),
    'el documento no está etiquetado');
});

/* --- Rutas especiales ----------------------------------------------------------- */

test('P14 y P15 conservan sus rutas propias', async () => {
  const { projectHref } = await modulo('src/lib/rutas.ts');
  assert.equal(projectHref('14', 'granular'), '/granular');
  assert.equal(projectHref('15', 'urban-challenge'), '/caso/urban-challenge');
});

test('los siete pilares de GRANULAR tienen página', async () => {
  const { pillars } = await modulo('src/content/granular.ts');
  assert.equal(pillars.length, 7);
  const ids = pillars.map((p) => p.id);
  assert.deepEqual(ids, ['agua', 'agropecuario', 'gobernanza', 'socioeconomia',
    'ambiente', 'conectividad', 'clustering']);
});

/* --- Composición ---------------------------------------------------------------- */

test('el rótulo de proyecto se mide contra su columna, no contra el viewport', () => {
  const css = readFileSync('src/components/proyecto/Proyecto.module.css', 'utf8');
  // `cqw` es el ancho real de la columna: es lo que impide que «Geomorfología»
  // se meta debajo de la obra.
  assert.match(css, /--palabra/, 'el rótulo no considera la palabra más larga');
  assert.match(css, /100cqw/, 'el rótulo no se mide contra su contenedor');
  assert.match(css, /container-type: inline-size/);
});

test('el amarillo de señal no se usa como tinta sin variante legible', () => {
  const ctrl = readFileSync('src/styles/controles.css', 'utf8');
  assert.match(ctrl, /--senal-texto/,
    'el control activo usaría amarillo puro, ilegible sobre papel');
});

/* --- Utilidad -------------------------------------------------------------------- */

/** Importa un módulo TypeScript del proyecto transpilándolo al vuelo. */
async function modulo(ruta) {
  const ts = (await import('typescript')).default;
  const js = ts.transpileModule(readFileSync(ruta, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
  }).outputText;
  return import(`data:text/javascript,${encodeURIComponent(js)}`);
}
